services:
  - type: web
    name: vipvast-backend
    env: python
    plan: free
    region: virginia
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    pythonVersion: "3.11"
