services:
  - type: web
    name: vipvast-alerts
    env: python
    plan: free
    region: virginia
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: true
    branch: main
